### PR TITLE
debugserver: Fix service startup for iOS 14b4+

### LINKED ISSUE #1027: Port fix for iOS 14b4+startup to libimobiledevice-win32
Please port the below commit to the libimobiledevice-win32 fork so the debug server can work correctly for iOS 14 devices.

### PR DESCRIPTION
**Pull request by mauroa**
Por from base repo: https://github.com/libimobiledevice/libimobiledevice/commit/98056a89648f431759c5fa4ed87c6ea6ba0cdd3f

Attempt to fix https://github.com/libimobiledevice/libimobiledevice/issues/1027 and also fix debug issues with the Windows version and iOS 14

### CODE REVIEW

**Comment by mauroa** [comment]
@qmfrederik could you please review?

**Comment by qmfrederik** [comment]
@mauroa I rebased the fork on top of upstream master. Should now contain this fix.

For my curiosity, how do you consume the output of this project? Do you compile yourself, use the Azure DevOps build output or the NuGet package?

**Comment by mauroa** [comment]
Thanks @qmfrederik. I'm consuming the imobiledevice-net package

**Comment by qmfrederik** [comment]
Thanks, I'll update that package when https://dev.azure.com/libimobiledevice-win32/imobiledevice-net/_build/results?buildId=1098&view=logs&j=4fbced83-508e-5fe0-c978-5c71ec0fc506 completes - may take a while, ping me if it's not up by the end of the week.

**Comment by mauroa** [comment]
Awesome, thanks!

**Pull request closed without merging**
